import type { Metadata } from "next";
import { Geist, Geist_Mono, Pacifico, AR_One_Sans } from "next/font/google";
import "./globals.css";

// Import AR One Sans from Google Fonts
const arOneSans = AR_One_Sans({
  variable: "--font-ar-one-sans",
  subsets: ["latin"],
  weight: ["400", "700"]
});

const pacifico = Pacifico({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-pacifico',
})

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "B2BNet",
  description: "Generated by B2BNet",
  icons: {
    icon: [
      { url: '/logoico.png', sizes: 'any' },
      { url: '/logoico.png', sizes: '16x16', type: 'image/png' },
      { url: '/logoico.png', sizes: '32x32', type: 'image/png' },
    ],
    shortcut: '/logoico.png',
    apple: '/logoico.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${pacifico.variable} ${arOneSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
